# DESAFIO 1
**Datasets_Jhoan Daniela Henao Garcia**

**1.	Bases de datos de índices de felicidad, muerte y suicidio**

**Definición**

El Informe Mundial de la Felicidad es una publicación de la Red de Soluciones de Desarrollo Sostenible, impulsada por los datos de la Encuesta Mundial de Gallup. El Informe Mundial de la Felicidad refleja una demanda mundial de más atención a la felicidad y el bienestar como criterios para la política gubernamental. Revisa el estado de la felicidad en el mundo actual y muestra cómo la ciencia de la felicidad explica las variaciones personales y nacionales en la felicidad.
Se quiere comprobar como el nivel de felicidad llega a influir en las enfermedades que llegan a ser terminales, incluyendo la tasa de suicidio considerando las enfermedades mentales.

**Descripción de los datos**

los datos se encuentran inicialmente en tres datasets importados desde Kaggle en formato .csv, los cuales son:

I.	Cause_Death: dataset con datos causa de muertes por país y por año (1990-2019).

II.	Hapinnes: dataset en el que se usa datos recolectados en encuestas en los cuales se observa teniendo en cuenta las seis variables y estimaciones de sus asociaciones con evaluaciones de vida para explicar la variación entre países. Incluyen el PIB per cápita, el apoyo social, la esperanza de vida saludable, la libertad, la generosidad y la corrupción, este dataset contiene información desde el 2005 hasta el 2022.

III.	Suicide Raw Data: dataset con datos los suicidos ocurridos en diferentes países y años (1985-2016), diferenciando rangos de edad y sexo.

La descripción de cada uno de los campos del dataset es la siguiente:

|Campo|Descripción|Tipo|
|:------|:-----------|:----|
|Country Name|Nombre del País|String|
|Regional Indicator|Ubicación en el Continente|String|
|Year|Año|Int|
|Life Ladder|Esto se llama la escalera de Cantril: pide a los encuestados que piensen en una escalera, siendo la mejor vida posible para ellos un 10 y la peor vida posible un 0. Luego se les pide que califiquen sus propias vidas actuales en ese 0 a 10 escala|Float|
|Log GDP Per Capita|El registro del PIB per cápita|Float|
|Social Support|El apoyo social (0-1) es el promedio nacional de las respuestas binarias (0=no, 1=sí) a la pregunta de la Encuesta mundial Gallup (GWP) “Si estuviera en problemas, ¿tiene familiares o amigos a los que pueda ayudar? contar para ayudarte cuando los necesites, ¿o no?|Float|
|Healthy Life Expectancy at Birth|La serie temporal de Esperanza de vida sana al nacer se construye a partir de datos del repositorio de datos del Observatorio de la Salud Mundial de la Organización Mundial de la Salud (OMS)|Float|
|Freedom To Make Life Choices|La libertad para tomar decisiones en la vida (0-1) es el promedio nacional de respuestas binarias a la pregunta de GWP "¿Está satisfecho o insatisfecho con su libertad para elegir lo que hace con su vida?"|Float|
|Generosity|La generosidad es el residuo de la regresión del promedio nacional de las respuestas de GWP a la pregunta de donación "¿Ha donado dinero a una organización benéfica en el último mes?" sobre el logaritmo del PIB per cápita.|Float|
|Perceptions Of Corruption|Las percepciones de corrupción (0-1) son el promedio de respuestas binarias a dos preguntas de GWP: "¿Está la corrupción generalizada en todo el gobierno o no?" y "¿Está la corrupción generalizada dentro de las empresas o no?" Cuando faltan datos sobre corrupción gubernamental, se utiliza la percepción de corrupción empresarial como medida general de percepción de corrupción.|Float|
|Positive Affect|El afecto positivo se define como el promedio de las medidas de efectos del día anterior para la risa, el disfrute y el interés|Float|
|Negative Affect|El afecto negativo se define como el promedio de las medidas de los efectos del día anterior para la preocupación, la tristeza y la ira.|Float|
|Confidence In National Government|Nivel de confianza que se tiene en el gobierno|Float|

In [2]:
import pandas as pd
import os
cwd = os.getcwd()
print(cwd)
Happiness = pd.read_csv(filepath_or_buffer="./Happiness&Death&Suicide\Happiness.csv")
Happiness.head(5)

C:\Users\danih\OneDrive - Politecnico Internacional\Documentos\CoderHouse\Data Science\Desafio 1

,Country Name,Regional Indicator,Year,Life Ladder,Log GDP Per Capita,Social Support,Healthy Life Expectancy At Birth,Freedom To Make Life Choices,Generosity,Perceptions Of Corruption,Positive Affect,Negative Affect,Confidence In National Government
0,Afghanistan,South Asia,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.167652,0.881686,0.414297,0.258195,0.612072
1,Afghanistan,South Asia,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.190809,0.850035,0.481421,0.237092,0.611545
2,Afghanistan,South Asia,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.121316,0.706766,0.516907,0.275324,0.299357
3,Afghanistan,South Asia,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.163571,0.731109,0.479835,0.267175,0.307386
4,Afghanistan,South Asia,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.237588,0.775620,0.613513,0.267919,0.435440

In [3]:
Happiness = pd.read_csv(filepath_or_buffer="./Happiness&Death&Suicide\Cause_Death.csv")
Happiness.head(5)

,Country/Territory,Code,Year,Meningitis,Alzheimer's Disease and Other Dementias,Parkinson's Disease,Nutritional Deficiencies,Malaria,Drowning,Interpersonal Violence,...,Diabetes Mellitus,Chronic Kidney Disease,Poisonings,Protein-Energy Malnutrition,Road Injuries,Chronic Respiratory Diseases,Cirrhosis and Other Chronic Liver Diseases,Digestive Diseases,"Fire, Heat, and Hot Substances",Acute Hepatitis
0,Afghanistan,AFG,1990,2159,1116,371,2087,93,1370,1538,...,2108,3709,338,2054,4154,5945,2673,5005,323,2985
1,Afghanistan,AFG,1991,2218,1136,374,2153,189,1391,2001,...,2120,3724,351,2119,4472,6050,2728,5120,332,3092
2,Afghanistan,AFG,1992,2475,1162,378,2441,239,1514,2299,...,2153,3776,386,2404,5106,6223,2830,5335,360,3325
3,Afghanistan,AFG,1993,2812,1187,384,2837,108,1687,2589,...,2195,3862,425,2797,5681,6445,2943,5568,396,3601
4,Afghanistan,AFG,1994,3027,1211,391,3081,211,1809,2849,...,2231,3932,451,3038,6001,6664,3027,5739,420,3816

In [4]:
Happiness = pd.read_csv(filepath_or_buffer="./Happiness&Death&Suicide/Suicide Raw Data.csv")
Happiness.head(5)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

**2.	Video Games Sales**

**Definición**

Gracias a este conjunto de datos, los cuales nos proporciona una excelente data de los 100 videojuegos más vendidos, junto con sus respectivas plataformas, géneros y editores. Al analizar los datos proporcionados en este conjunto de datos de Kaggle, queremos obtener cuáles fueron los juegos con mayor popularidad en las diferentes plataformas y los géneros más exitosos asociados con esas plataformas. Además, qué editoriales han logrado el éxito en publicaciones de series múltiples o incluso títulos únicos.

**Descripción de los dato**

los datos se encuentran inicialmente en un dataset importados desde Kaggle en formato .csv: 
Video Games: dataset con datos de los videojuegos lanzados desde 1980 hasta 2020, diferenciados por plataforma, género y empresa que publicó para obtener un detalle de las ventas realizadas en Norte América, Japón, Europa y otras partes del mundo.

|Campo| Descripción|	Tipo|
|:------|:------------|:--------|
|Rank|	Conteo de videojuegos|	Int|
|Name|	Nombre del videojuego|	String|
|Platform|	Plataforma en que se encuentra el video jeugo|	String|
|Year|	Año|	Int|
|Genre|	Género del videojuego|	String|
|Publisher|	Quien publicó el videojuego|	String|
|NA_Sales|	Ventas en Norte América|	Float|
|EU_Sales|	Ventas en Europa|	Float|
|JP_Sales|	Ventas en Japón|	Float|
|Other_Sales|	Ventas en otras partes del mundo|	Float|
|Global_Sales|	Ventas Globales|	Float|

In [5]:
Happiness = pd.read_csv(filepath_or_buffer="./Video Games/Video Games.csv")
Happiness.head(5)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37

**3.	Chess**

**Definición**

Contamos con 2 datasets con más de 40.000 jugadas diferentes de Ajedrez online del año 2016, separadas por inteligencia artificial y jugadores reales, nos ayudará mostrar que jugadas pueden ayudarnos a ganar en menos movimientos. Además de poder hacer un análisis completo de cuantos juegos terminan en los diferentes tipos de jugadas, saber cuál es el Top 10 de jugadas y jugadores, y realizar una comparación entre los jugadores artificiales y los reales.

**Descripción de los datos**

los datos se encuentran inicialmente en un dataset importados desde Kaggle en formato .csv

|Campo|	Descripción|	Tipo|
|:------|:------------|:--------|
|Game|	Nombre del Juego|	String|
|White|	Jugador Blanco|	String|
|Black|	Jugador Negro|	String|
|White Elo|	Puntaje del jugador Blanco|	Int|
|Black Elo|	Puntaje del jugador Negro|	Int|
|White RD|	Desviación del puntaje del jugador Blanco|	Float|
|Black RD|	Desviación del puntaje del jugador Negro|	Float|
|WhiteIsComp|	¿El jugador Blanco es Computador?|	Booleano|
|BlackIsComp|	¿El jugador Negro es Computador?|	Booleano|
|TimeControl|	Tiempo que recibe el jugador al completar el juego|	Time|
|Date|	Fecha del juego|	Date|
|Time|	Hora del juego|	Time|
|White Clock|	Reloj para jugador Blanco|	Time|
|Black Clock|	Reloj para jugador Negro|	Time|
|ECO|	Entrada del juego|	String|
|PlyCount|	Conteo de jugadas|	Int|
|Result|	Resultado en puntaje|	Int|
|Result|	Resultado|	String|
|Commentaries|	Razones de finalizar el juego|	String|
|Moves|	Todos los movimientos del juego|	String|

In [6]:
Happiness = pd.read_csv(filepath_or_buffer="./Chess/2016_CvC.csv")
Happiness.head(5)

,Game,White,Black,White Elo,Black Elo,White RD,Black RD,WhiteIsComp,BlackIsComp,TimeControl,Date,Time,White Clock,Black Clock,ECO,PlyCount,Result,Result-Winner,Commentaries,Moves
0,"""zerowin"" vs ""GeidiPrime""",zerowin,GeidiPrime,2848,2464,0.0,0.0,Yes,Yes,900+0,2016.12.31,23:17:00,15:00.0,15:00.0,A30,72,1/2-1/2,Draw,Game drawn by mutual agreement,1. c4 c5 2. Nf3 e6 3. g3 b6 4. Bg2 Bb7 5. O-O ...
1,"""GeidiPrime"" vs ""SlowBox""",GeidiPrime,SlowBox,2455,2511,0.0,0.0,Yes,Yes,900+0,2016.12.31,20:25:00,15:00.0,15:00.0,D01,127,1-0,White,Black checkmated,1. d4 Nf6 2. Nc3 d5 3. Bg5 Nbd7 4. Nf3 h6 5. B...
2,"""zerowin"" vs ""GeidiPrime""",zerowin,GeidiPrime,2846,2457,0.0,0.0,Yes,Yes,900+0,2016.12.31,20:03:00,15:00.0,15:00.0,A40,77,1-0,White,Black resigns,1. d4 e6 2. c4 Bb4+ 3. Bd2 Bxd2+ 4. Qxd2 Nf6 5...
3,"""GeidiPrime"" vs ""zerowin""",GeidiPrime,zerowin,2459,2844,0.0,0.0,Yes,Yes,900+0,2016.12.31,19:25:00,15:00.0,15:00.0,C11,128,0-1,Black,White resigns,1. d4 Nf6 2. Nc3 d5 3. Bg5 e6 4. e4 dxe4 5. Nx...
4,"""FishTest"" vs ""GeidiPrime""",FishTest,GeidiPrime,3033,2459,0.0,0.0,Yes,Yes,900+0,2016.12.31,18:42:00,15:00.0,15:00.0,C07,131,1-0,White,Black resigns,1. e4 e6 2. d4 d5 3. Nd2 c5 4. exd5 Qxd5 5. dx...

In [7]:
Happiness = pd.read_csv(filepath_or_buffer="./Chess/2016_CvH.csv")
Happiness.head(5)

,Game,White,Black,White Elo,Black Elo,White RD,Black RD,WhiteIsComp,BlackIsComp,TimeControl,Date,Time,White Clock,Black Clock,ECO,PlyCount,Result,Result-Winner,Commentaries,Moves
0,"""Knightsmasher"" vs ""LuvDino""",Knightsmasher,LuvDino,2594,2041,0.0,0.0,Yes,No,120+0,2016.12.31,23:48:00,02:00.0,02:00.0,B08,93,1-0,White,Black forfeits on time,1. d4 Nf6 2. Nf3 g6 3. Nc3 Bg7 4. e4 d6 5. Be2...
1,"""Ashokag"" vs ""MortimerBlackwell""",Ashokag,MortimerBlackwell,1593,2416,0.0,0.0,No,Yes,1200+10,2016.12.31,23:21:00,20:00.0,20:00.0,B10,43,0-1,Black,White forfeits by disconnection,1. e4 c6 2. d3 d5 3. Nf3 Bg4 4. Be2 Nf6 5. h3 ...
2,"""MortimerBlackwell"" vs ""Gschach""",MortimerBlackwell,Gschach,2416,1681,0.0,0.0,Yes,No,1800+10,2016.12.31,22:55:00,30:00.0,30:00.0,C41,19,1-0,White,Black resigns,1. e4 e5 2. Nf3 d6 3. d4 Be7 4. dxe5 Bg4 5. Bb...
3,"""Sillycon"" vs ""Estepario""",Sillycon,Estepario,2373,2185,0.0,0.0,Yes,No,900+0,2016.12.31,22:55:00,15:00.0,15:00.0,B06,35,1-0,White,Black resigns,1. d4 d6 2. e4 g6 3. Nc3 Bg7 4. Be3 Nd7 5. f4 ...
4,"""LuvDino"" vs ""pikozrout""",LuvDino,pikozrout,2027,2228,0.0,0.0,No,Yes,120+1,2016.12.31,22:23:00,02:00.0,02:00.0,B57,91,1-0,White,Black checkmated,1. e4 c5 2. Nf3 d6 3. Bc4 Nf6 4. Nc3 Nc6 5. d4...